# Generated by Django 4.1 on 2022-08-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ads",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=400)),
                ("author", models.CharField(max_length=400)),
                ("price", models.FloatField()),
                ("description", models.CharField(max_length=2000)),
                ("address", models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
