# Generated by Django 4.1 on 2022-08-13 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_ads_is_published"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ads",
            name="is_published",
        ),
    ]
